### ISSUE TITLE
Бесконечное подключение или "я же вас и тут достану"

### ISSUE THREAD

**Issue by GGLOVV** [frosty-dev/ss14-feedback#7]
Захожу на любой сервер вайт дрим и в 9 из 10 случаев сажусь на бесконечное подключение с ошибкой в консоли

Быть мной.

Дайте мне зайти бля

[DEBG] root: Switching to state Content.Client.Launcher.LauncherConnecting
[ERRO] discord: Failed connection to discord-ipc-0. The operation has timed out.
[DEBG] client: Runlevel changed to: Connecting
[DEBG] net: Attempting to connect to s0.ss14.su port 6666
[WARN] eng: MainLoop: Cannot keep up!
[DEBG] net: First attempt IP address is 136.243.75.37, second attempt 
[DEBG] net: "136.243.75.37:6666": Status changed to InitiatedConnect, reason: "user called connect"
[DEBG] net: "136.243.75.37:6666": Status changed to Connected, reason: "Connected to 9611AA0E04A985F4"
[DEBG] net: Handshake completed, connection established.
[INFO] net: Received message name string table.
[INFO] net: Client completed serializer handshake.
[INFO] cfg: Sending client info...
[DEBG] client: Synchronized time base: 1: 00:00:00
[INFO] clyde.oal: Set audio attenuation to InverseDistanceClamped
[ERRO] net: 136.243.75.37:6666: exception in message handler for MsgPreferencesAndSettings:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Robust.Shared.GameObjects.EntitySystemManager.GetEntitySystem[T]() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 66
   at Robust.Shared.GameObjects.EntityManager.System[T]() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Systems.cs:line 9
   at Content.Client.Lobby.UI.LobbyCharacterPreviewPanel.UpdateUI() in /home/runner/work/ss14-new/ss14-new/Content.Client/Lobby/UI/LobbyCharacterPreviewPanel.cs:line 143
   at Content.Client.Preferences.ClientPreferencesManager.HandlePreferencesAndSettings(MsgPreferencesAndSettings message) in /home/runner/work/ss14-new/ss14-new/Content.Client/Preferences/ClientPreferencesManager.cs:line 115
   at Robust.Shared.Network.NetManager.<>c__DisplayClass106_0`1.<RegisterNetMessage>b__0(NetMessage msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 957
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 906
[DEBG] admin: Have 21 commands available
[INFO] admin: Updated admin status: Not admin
[DEBG] admin: Have 21 commands available
[INFO] admin: Updated admin status: False/Event Master | Дамоклов Меч/ADMIN|DEBUG|FUN|SPAWN|VAREDIT|MAPPING|ROUND|QUERY|ADMINHELP
[DEBG] client: Runlevel changed to: Connected
[ERRO] net: 136.243.75.37:6666: exception in message handler for MsgPlayerList:
System.InvalidOperationException: Subscription locked.
   at Robust.Shared.GameObjects.EntityEventBus.EntAddSubscription(CompIdx compType, Type compTypeObj, Type eventType, DirectedRegistration registration) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 352
   at Robust.Shared.GameObjects.EntityEventBus.EntSubscribe[TEvent](CompIdx compType, Type compTypeObj, Type eventType, DirectedEventHandler`1 handler, OrderingData order, Boolean byReference) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 389
   at Robust.Shared.GameObjects.EntityEventBus.SubscribeLocalEvent[TComp,TEvent](ComponentEventHandler`2 handler, Type orderType, Type[] before, Type[] after) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 259
   at Robust.Shared.GameObjects.EntitySystem.SubscribeLocalEvent[TComp,TEvent](ComponentEventHandler`2 handler, Type[] before, Type[] after) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.Subscriptions.cs:line 117
   at Robust.Shared.Physics.Systems.FixtureSystem.Initialize() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Physics/Systems/FixtureSystem.cs:line 29
   at Robust.Shared.GameObjects.EntitySystemManager.Initialize(Boolean discover) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 185
   at Robust.Shared.GameObjects.EntityManager.Startup() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.cs:line 221
   at Robust.Client.BaseClient.GameStartedSetup() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/BaseClient.cs:line 248
   at Robust.Client.BaseClient.OnPlayerJoinedServer(ICommonSession session) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/BaseClient.cs:line 205
   at Robust.Client.BaseClient.OnLocalStatusChanged(Object obj, StatusEventArgs eventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/BaseClient.cs:line 272
   at Robust.Client.Player.LocalPlayer.SwitchState(SessionStatus oldStatus, SessionStatus newStatus) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Player/LocalPlayer.cs:line 138
   at Robust.Client.Player.PlayerManager.UpdatePlayerList(IEnumerable`1 remotePlayers) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Player/PlayerManager.cs:line 217
   at Robust.Client.Player.PlayerManager.HandlePlayerList(MsgPlayerList msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/Player/PlayerManager.cs:line 165
   at Robust.Shared.Network.NetManager.<>c__DisplayClass106_0`1.<RegisterNetMessage>b__0(NetMessage msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 957
   at Robust.Shared.Network.NetManager.DispatchNetMessage(NetIncomingMessage msg) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Network/NetManager.cs:line 906
[DEBG] res.mod: RESOLVING DEFAULT: System.Net.Sockets.resources, Version=7.0.0.0, Culture=ru-RU, PublicKeyToken=b03f5f7f11d50a3a
[DEBG] res.mod: RESOLVING DEFAULT: System.Net.Sockets.resources, Version=7.0.0.0, Culture=ru, PublicKeyToken=b03f5f7f11d50a3a
[WARN] eng: MainLoop: Cannot keep up!

Чистка кэша - не помогает
Чистка движков - не помогает
Переустановка игры - не помогает
Смена интернет подключения - помогало 2 дня и все
deadmin - помог 2 раза и все
Ищу решение без смены винды(она кстати 10)

**Comment by Aviu00** [comment]
Попробуй удалить и заново создать перса

**Comment by GGLOVV** [comment]
Ты точно то открыл? Бесконечное подключение на сервер, при чем тут персонажи?

**Comment by Aviu00** [comment]
Ну раз не хочешь, не надо тогда
